// Repositorio de Disciplinas V20
// Fuente: knowledge_base/localizationAndRepository.js
window.DISCIPLINE_REPO = [
  { id: 1, name_es: "Abombwe", name_en: "Abombwe" },
  { id: 2, name_es: "Animalismo", name_en: "Animalism" },
  { id: 3, name_es: "Auspex", name_en: "Auspex" },
  { id: 4, name_es: "Bardo", name_en: "Bardo" },
  { id: 5, name_es: "Celeridad", name_en: "Celerity" },
  { id: 6, name_es: "Daimoinon", name_en: "Daimoinon" },
  { id: 7, name_es: "Deimos", name_en: "Deimos" },
  { id: 8, name_es: "Dementación", name_en: "Dementation" },
  { id: 9, name_es: "Dominación", name_en: "Dominate" },
  { id: 10, name_es: "Extinción", name_en: "Quietus" },
  { id: 11, name_es: "Fortaleza", name_en: "Fortitude" },
  { id: 12, name_es: "Hechiceria Assamita", name_en: "Assamite Sorcery" },
  { id: 13, name_es: "Hechiceria Kuldúnica", name_en: "Koldunic Sorcery" },
  { id: 14, name_es: "Hechiceria Nahuallotl", name_en: "Nahuallotl Sorcery" },
  { id: 15, name_es: "Hechiceria Sadhana", name_en: "Sadhana Sorcery" },
  { id: 16, name_es: "Hechiceria Setita", name_en: "Setite Sorcery" },
  { id: 17, name_es: "Hechiceria Wanga", name_en: "Wanga Sorcery" },
  { id: 18, name_es: "Kami", name_en: "Kami" },
  { id: 19, name_es: "Kinetismo", name_en: "Kineticism" },
  { id: 20, name_es: "Maleficia", name_en: "Maleficia" },
  { id: 21, name_es: "Melpómene", name_en: "Melpomene" },
  { id: 22, name_es: "Mortis", name_en: "Mortis" },
  { id: 23, name_es: "Mysthercería", name_en: "Mytherceria" },
  { id: 24, name_es: "Necromancia", name_en: "Necromancy", hasSendas: true },
  { id: 25, name_es: "Nihilistica", name_en: "Nihilistic" },
  { id: 26, name_es: "Obeah", name_en: "Obeah" },
  { id: 27, name_es: "Obtenebración", name_en: "Obtenebration" },
  { id: 28, name_es: "Ogham", name_en: "Ogham" },
  { id: 29, name_es: "Ofuscación", name_en: "Obfuscate" },
  { id: 30, name_es: "Potencia", name_en: "Potence" },
  { id: 31, name_es: "Presencia", name_en: "Presence" },
  { id: 32, name_es: "Protean", name_en: "Protean" },
  { id: 33, name_es: "Quimerismo", name_en: "Chimerstry" },
  { id: 34, name_es: "Sanguinus", name_en: "Sanguinus" },
  { id: 35, name_es: "Serpentis", name_en: "Serpentis" },
  { id: 36, name_es: "Spiritus", name_en: "Spiritus" },
  { id: 37, name_es: "Striga", name_en: "Striga" },
  { id: 38, name_es: "Tanatosis", name_en: "Thanatosis" },
  { id: 39, name_es: "Taumaturgia", name_en: "Thaumaturgy", hasSendas: true },
  { id: 40, name_es: "Temporis", name_en: "Temporis" },
  { id: 41, name_es: "Valeren", name_en: "Valeren" },
  { id: 42, name_es: "Vicisitud", name_en: "Vicissitude" },
  { id: 43, name_es: "Visceratika", name_en: "Visceratika" },
  { id: 44, name_es: "Vuelo", name_en: "Flight" },
];
